DROP TABLE CLAIM_DETAILS;
DROP TABLE CLAIM_QUESTIONS;
DROP TABLE CLAIM;
DROP TABLE POLICY;
DROP TABLE ACCOUNTS;
DROP TABLE USER_ROLE;

 


DROP SEQUENCE CLAIM_SEQ;
DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE POLICY_SEQ;