CREATE TABLE CLAIM_DETAILS(
CLAIM_NUMBER NUMBER(10) CONSTRAINT FK_CLAIM_NUMBER_inClaimDetails REFERENCES CLAIM(CLAIM_NUMBER) ON DELETE CASCADE, 
QUESTION_ID NUMBER(10) CONSTRAINT FK_QUESTION_ID_inClaimDetails REFERENCES CLAIM_QUESTIONS(QUESTION_ID) ON DELETE CASCADE,
ANSWER VARCHAR2(80));
COMMIT;
